import { library } from "@fortawesome/fontawesome-svg-core";
import {
  
    faA, faB, faC, faD, faE, faF, faG, faH, faI, faJ, faK, faL, faM, faN, faO, faP, faQ, faR, faS, faT, faU, faV, faW, faX, faY, faZ,
    faArrowRight,
    faArrowLeft,
    faHome,
    faAddressCard,
    faEnvelope,
    faPhone,
    faPaperPlane,
    faLocationDot,
    faImage,
    faBlog,
    faAt,
    faEyeSlash,
    faChevronLeft,
    faChevronDown,
    faSpinner,
    faHouse,
    faRightFromBracket,
    faGlobe,
    faGauge,
    faVideo,
    faMagnifyingGlass,
    faPen,
    faPlus,
    faClock,
    faEnvelopesBulk,
    faPlaneDeparture,
    faUsers,
    faRecycle,
    fa0,
    faArrowRotateLeft,
    
    faUsersGear,
    faPanorama,
    faUserShield,
    faFingerprint,
    faGear,
    faBriefcase,
    faMobileScreen,
    faCopyright,
    faMapLocationDot,
    
    faStarHalf,
    faCodeBranch,
    faMap,
    faCalendar,
    faCalendarDays,
    } from "@fortawesome/free-solid-svg-icons";
import {
    
    faAddressBook,
    faTrashCan,
    faUser,
    faComment,
    faTrashAlt,
    faEnvelopeOpen
    
} from "@fortawesome/free-regular-svg-icons";

import { faFacebookF, faWhatsapp ,faYoutube} from "@fortawesome/free-brands-svg-icons";

import {
    FontAwesomeIcon,
    FontAwesomeLayers,
    FontAwesomeLayersText,
} from "@fortawesome/vue-fontawesome";
library.add(
    faMap,
    faCodeBranch,
    faStarHalf,
    faGear,faYoutube,
    faCopyright,
    faMapLocationDot,
    faBriefcase,faMobileScreen,
    faUserShield,
    faFingerprint,
    faPanorama,
    faUsersGear,
    faRecycle,
    faArrowRotateLeft,
    faTrashCan,
     faA, faB, faC, faD, faE, faF, faG, faH, faI, faJ, faK, faL, faM, faN, faO, faP, faQ, faR, faS, faT, faU, faV, faW, faX, faY, faZ,fa0,
    faArrowRight,
    faUsers,
    faPlaneDeparture,
    faHome,
    faAddressCard,
    faEnvelope,
    faEnvelopeOpen,
    faEnvelopesBulk,    
    faPhone,
    faFacebookF,
    faWhatsapp,
    faPaperPlane,
    faLocationDot,
    faClock,
    faImage,
    faBlog,
    faArrowLeft,
    faAt,
    faEyeSlash,
    faUser,
    faChevronLeft,
    faChevronDown,
    faSpinner,
    faHouse,
    faRightFromBracket,
    faGlobe,
    faGauge,
    faVideo,
    faMagnifyingGlass,
    faComment,
    faPen,
    faTrashAlt,
    faPlus,
    faCalendar,
    faCalendarDays

);


export  { FontAwesomeIcon,
    FontAwesomeLayers,
    FontAwesomeLayersText };